- name: Set ASDF directory
  set_fact:
    asdf_dir: "/home/{{ username }}/.asdf"

- name: Check if Go is installed
  command: /usr/local/go/bin/go version
  register: go_check
  ignore_errors: true

- name: Install asdf using Go
  become: false
  ansible.builtin.shell: |
    /usr/local/go/bin/go install github.com/asdf-vm/asdf/cmd/asdf@latest
  args:
    executable: /bin/bash
    creates: "/home/{{ username }}/go/bin/asdf"
  environment:
    GOPATH: "/home/{{ username }}/go"
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}:/home/{{ username }}/go/bin"
  when: go_check.rc == 0

- name: Create asdf bin directory
  ansible.builtin.file:
    path: "{{ asdf_dir }}/bin"
    state: directory
    mode: '0755'

- name: Check if asdf binary was installed by Go
  ansible.builtin.stat:
    path: "/home/{{ username }}/go/bin/asdf"
  register: asdf_go_bin

- name: Move compiled asdf binary to .asdf/bin
  ansible.builtin.copy:
    remote_src: true
    src: "/home/{{ username }}/go/bin/asdf"
    dest: "{{ asdf_dir }}/bin/asdf"
    mode: '0755'
  when: asdf_go_bin.stat.exists

- name: Ensure completions directory exists
  ansible.builtin.file:
    path: "{{ asdf_dir }}/completions"
    state: directory
    mode: '0755'

- name: Download asdf completions file
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/asdf-vm/asdf/master/internal/completions/asdf.bash'
    dest: "{{ asdf_dir }}/completions/asdf.bash"
    mode: '0644'

- name: Get user shell from /etc/passwd
  command: "getent passwd {{ username }}"
  register: user_passwd

- name: Extract shell from getent output
  set_fact:
    user_shell: "{{ user_passwd.stdout.split(':')[-1] | trim }}"

- name: Set shell init file
  set_fact:
    shell_rc_file: >-
      {{ "/home/" + username + "/.zshrc" if "zsh" in user_shell else "/home/" + username + "/.bashrc" }}

- name: Add ASDF configuration to shell init file
  ansible.builtin.lineinfile:
    path: "{{ shell_rc_file }}"
    line: '{{ item }}'
    create: true
    insertafter: EOF
  loop:
    - 'export ASDF_DIR="{{ asdf_dir }}"'
    - '. "$ASDF_DIR/asdf.sh"'
    - '. "$ASDF_DIR/completions/asdf.bash"'
